### ISSUE TITLE
EmonTx Code Guide no longer accessible

### ISSUE THREAD

**Issue by madnat** [openenergymonitor/emontx-shield#1]
none of these references work (links broken)  in https://github.com/openenergymonitor/emontx-shield/tree/master/firmware#emontx-code-guide

links at 01-08 result in error 404

emonTx Code guide

The EmonTx code guide goes through main components required to put a full emontx firmware together. It's recommended that you work through these examples first so that you have a good understanding of how the full firmware's work.

01 - Single CT
02 - Second CT
03 - AC Voltage
04 - Temperature
05 - Pulse Counting
06 - Elster Meter
07 - Transmitting Data
08 - Watchdog

**Comment by glynhudson** [comment]
Thanks for, letting us know. The links have now been fixed. The code guide is now in the emontx2 repo: https://github.com/openenergymonitor/emontx2/tree/master/firmware/Guide
