### ISSUE TITLE
Power Arduino from AC input

### ISSUE THREAD

**Issue by richardtector** [openenergymonitor/emontx-shield#2]
In a similar fashion to the emonTx v3 board, is it feasible to add a voltage regulator and supporting electronics to provide a 5V DC supply back to the host Arduino from the LV AC reference input? This would remove the need for a second PSU.

Thanks,

Richard

**Comment by glynhudson** [comment]
I'm afraid the power requirement for an Arduino Uno is too high to be provided by a AC-DC half-wave circuit without causing a negative effect to the AC waveform. See this blog post for how the AC-DC half-wave circuit works: https://blog.openenergymonitor.org/2012/05/emontx-single-ac-power-supply/
